spin_manifest_version = 2

[application]
authors = ["Glenn Lewis"]
description = "A simple Spin application written in MoonBit."
name = "llm"
version = "0.1.0"

[[trigger.http]]
component = "llm"
route = "/..."

[component.llm]
source = "llm.wasm"
ai_models = ["llama2-chat"]

[component.llm.build]
command = """\
  moon build --target wasm && \
  wasm-tools component embed .mooncakes/gmlewis/spin-moonbit-sdk/wit ./target/wasm/release/build/llm.wasm -o llm.wasm --encoding utf16 -w http-trigger && \
  wasm-tools component new llm.wasm -o llm.wasm
  """
watch = ["**/*.mbt"]
