spin_manifest_version = 2

[application]
authors = ["Glenn Lewis"]
description = "A simple Spin application written in MoonBit."
name = "now"
version = "0.1.0"

[[trigger.http]]
component = "now"
route = "/..."

[component.now]
source = "now.wasm"

[component.now.build]
command = """\
  moon build --target wasm && \
  wasm-tools component embed .mooncakes/gmlewis/spin-moonbit-sdk/wit ./target/wasm/release/build/now.wasm -o now.wasm --encoding utf16 -w http-trigger && \
  wasm-tools component new now.wasm -o now.wasm
  """
watch = ["**/*.mbt"]
